export const traderInventory = {
    bag: {
        gourd: 1,
        mirror: 1,
        macaron: 1,
        hole: 1,
        book: 1,
        centipede: 1,
        shampoo: 1,
        dryWater: 1,
        oldTrousers: 1,
        twistedTrinket: 1,
    },
    prices: {
        gourd: { buy: 1, sell: 1 },
        mirror: { buy: 3, sell: 3 },
        macaron: { buy: 2, sell: 2 },
        hole: { buy: 5, sell: 5 },
        book: { buy: 2, sell: 2 },
        centipede: { buy: 1, sell: 1 },
        shampoo: { buy: 2, sell: 2 },
        dryWater: { buy: 2, sell: 2 },
        oldTrousers: { buy: 1, sell: 1 },
        twistedTrinket: { buy: 4, sell: 4 },
        tomato: { buy: 1, sell: 1 },
        corn: { buy: 2, sell: 2 },
        beetroot: { buy: 3, sell: 3 },
        soap: { buy: 4, sell: 4 },
        watermelon: { buy: 5, sell: 5 },
        pipe: { buy: 8, sell: 8 },
        duck: { buy: 12, sell: 12 },
      },
    gold: 50, 
  };
